const actionType =  {
    GET_HOME: 'GET_HOME',
    SET_CUR_SONG_ID: 'SET_CUR_SONG_ID',
    LOADED_SOURCE: 'LOADED_SOURCE',
    LOADING: "LOADING",
    SET_CUR_SONG_DATA : 'SET_CUR_SONG_DATA',
    SET_ALBUM_SONG_DATA: 'SET_ALBUM_SONG_DATA',
    SET_RECENT : 'SET_RECENT',

    //music
    PLAY: 'PLAY',
    SET_ALBUM: 'SET_ALBUM',
    PLAY_LIST: 'PLAY_LIST',
}

export default actionType;